version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    steps:
      - run: brew install go berkeley-db leveldb libsodium maven haskell-stack && stack setup
      - checkout
      - run: make circleci-macos

